### ISSUE TITLE
VMs that include spaces in the name are not supported

### ISSUE THREAD

**Issue by Strappazzon** [JayMontana36/vBoxSysInfoMod#10] opened 2018-09-20 14:49 UTC
Let's say I have the following VMs:
 - Scambait
 - Scambait Windows 10

I open up vBoxSysInfoMod and when the program asks me to type the name of the VM I want to modify, I type: `Scambait Windows 10`. The program ignores everything after the first space and modifies **Scambait** instead.

Typing the name inside the quotes vBoxSysInfoMod (`"Scambait Windows 10"` in this case) doesn't work either.

---

EDIT: I used the ID of the machine instead and the program accepts it:

![Screenshot](https://linx.li/selif/ptvkm8h9.png)

I'd suggest to either add a line of text that informs the user to use the ID if their VM name includes a space or add the support to spaces.

**Comment by JayMontana36** [comment] 2018-09-20 15:38
This was a problem first introduced with the release of vBoxSysInfoMod v5 that had also made it into the release of vBoxSysInfoMod v5.1, however this was since found and fixed with the release of vBoxSysInfoMod v5.2 onwards; I've just tested vBoxSysInfoMod v6 and checked the relevant points of interest for this bug and everything is working as expected, without the need of using the vBox VM's UUID in place of the name.

Fix in vBoxSysInfoMod v5.2: https://github.com/JayMontana36/vBoxSysInfoMod/commit/9368bf09d6d2a80f6de778644ea000266c6e49d3#diff-ef0ddec11a0f78c82dcb141c2659f709
 - Line 21 - 
(Initial original fix)

Fix in vBoxSysInfoMod v6: https://github.com/JayMontana36/vBoxSysInfoMod/blob/c707e60ee03eae7e6f5a07e1d4d9ee535734ec22/vBox%20System%20Info%20Mod.bat
 - Line 50 -
(Same fix)

Other relevant locations: "ModifyVMprocess" in v5.2, "ModifyProcess" and "ResetProcess" in v6.

![101](https://user-images.githubusercontent.com/6281870/45829773-a0619c00-bcc9-11e8-8366-9ea221fd6d5c.PNG)
![102](https://user-images.githubusercontent.com/6281870/45829774-a0619c00-bcc9-11e8-9744-3ad7a0097016.PNG)
![103](https://user-images.githubusercontent.com/6281870/45829775-a0619c00-bcc9-11e8-8430-bac4f1e386f5.PNG)
![104](https://user-images.githubusercontent.com/6281870/45829776-a0619c00-bcc9-11e8-840b-eb5397b13a46.PNG)

**Comment by JayMontana36** [comment] 2018-09-20 16:45
Alright, so after adding in a VM called "Scambait" in order to try and replicate your scenario exactly, it seems what really happens is vBoxSysInfoMod basically does modify the VM named "Scambait Windows 10" as intended, however what happens afterwards is it then proceeds to launch or "power on" the VM named "Scambait" instead of "Scambait Windows 10", and if no VM named "Scambait" exists then nothing happens (it won't launch or power on any VM) and it proceeds to the end credits manu.

Bug in vBoxSysInfoMod v6, line 119: https://github.com/JayMontana36/vBoxSysInfoMod/blob/c707e60ee03eae7e6f5a07e1d4d9ee535734ec22/vBox%20System%20Info%20Mod.bat#L119
Problem/Issue: The lack of quotes surrounding %VMname%, not affecting the main base functionality of vBoxSysInfoMod, but it's "power on" VM functionality. Noted; will be fixed in a future release, thanks.

**Closed as completed by JayMontana36** 2018-09-20 16:45 UTC
Labels: bug
